# Generated by Django 3.1 on 2020-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=20, verbose_name='token'),
        ),
    ]
